### ISSUE TITLE
Atlas Authentication

### ISSUE THREAD

**Issue by cristina-grosu** [shivajid/DGI#5]
Hello! 

How is authentication supposed to be handled when accessing:

./bin/atlasclient --c=importmysql --mysqlhost=instance-35947.bigstep.io --password=password --username=root --db=default -createHiveTables -genLineage

I edited the atlasclient script to point to my atlas host: http://hostname:port/, but when I am trying to run the command specified above I get the following error:

db default
null
org.apache.atlas.AtlasServiceException: Metadata service API LIST_TYPES failed with status 401(Unauthorized) Response Body (<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 401 Full authentication is required to access this resource</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /api/atlas/types. Reason:
<pre>    Full authentication is required to access this resource</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
)
	at org.apache.atlas.AtlasClient.callAPIWithResource(AtlasClient.java:359)
	at org.apache.atlas.AtlasClient.callAPI(AtlasClient.java:364)
	at org.apache.atlas.AtlasClient.listTypes(AtlasClient.java:169)
	at com.hortonworks.atlas.adapter.AtlasTableInterface.<init>(AtlasTableInterface.java:71)
	at com.hortonworks.atlas.cli.AtlasCLI.importMysqlTables(AtlasCLI.java:590)
	at com.hortonworks.atlas.cli.AtlasCLI.<init>(AtlasCLI.java:269)
	at com.hortonworks.atlas.cli.AtlasCLI.main(AtlasCLI.java:64)

How can I fix it?

**Comment by vishalrana43** [comment]
I also had this same issue.
Can you please guide if you found solution of this issue.
Thank you.
